package-lock.json
src/components/CreateNewMeasure.tsx
src/components/MeasureLanding.tsx
src/madie-madie-measure.tsx
src/types/madie-components.d.ts

- Created a new measure page with basic styling, used reusable react components from madie-components.
- No test cases were added, as there is no functionality implemented.

Added Create new measure page

---

src/components/MeasureList.test.tsx
src/components/MeasureList.tsx

Jira Ticket: [MAT-3508](https://jira.cms.gov/browse/MAT-3508)
Added edit button, on click of this button use is navigated to "/measure/:id/edit" 

Added edit button on measure grid

---

src/components/MeasureLanding.tsx
src/components/NewMeasure.tsx
src/components/__tests__/InlineEdit.test.tsx
src/components/createNewMeasure/CreateNewMeasure.tsx

Jira Ticket: [MAT-0000](https://jira.cms.gov/browse/MAT-0000)

Fixed Styling issues related to Create New Measure page

---

src/__mocks__/@madie/madie-editor.tsx
src/components/MeasureEditor/MeasureEditor.test.tsx
src/components/MeasureEditor/MeasureEditor.tsx

Jira Ticket: [MAT-3533](https://jira.cms.gov/browse/MAT-3533) : Add CQL Editor into UI Workflow
Added missing test case for editor component
Added save/cancel buttons for editor which were missing and reported by QA

MAT-3533 Add CQL Editor into UI Workflow

---

src/components/EditMeasure/EditMeasure.test.tsx
src/components/EditMeasure/MeasureDetails/MeasureInformation.test.tsx
src/components/EditMeasure/MeasureDetails/MeasureInformation.tsx
src/components/EditMeasure/MeasureDetails/MeasureSteward.test.tsx
src/components/EditMeasure/MeasureDetails/MeasureSteward.tsx
src/components/EditMeasure/MeasureDetails/__snapshots__/MeasureInformation.test.tsx.snap
src/components/EditMeasure/MeasureDetails/__snapshots__/MeasureSteward.test.tsx.snap

Jira Ticket: [MAT-3513](https://jira.cms.gov/browse/MAT-3513)
Adding test coverage

MAT-3513: Adding test coverage

---

src/components/createNewMeasure/CreateNewMeasure.test.tsx
src/components/createNewMeasure/CreateNewMeasure.tsx
src/components/editMeasure/measureDetails/measureInformation/MeasureInformation.tsx
src/components/editMeasure/measureDetails/measureInformation/__snapshots__/MeasureInformation.test.tsx.snap
src/models/CreateNewMeasureModel.ts
src/models/Measure.ts
src/models/MeasureSchemaValidator.ts

Jira Ticket: [MAT-3520](https://jira.cms.gov/browse/MAT-3520): Save/Validate library name on create measure page 

MAT-3520: Save/Validate Library name on measure creation page

---

src/components/createNewMeasure/CreateNewMeasure.test.tsx
src/components/createNewMeasure/CreateNewMeasure.tsx
src/models/MeasureSchemaValidator.ts

Jira Ticket: [MAT-3651](https://jira.cms.gov/browse/MAT-3651): Measuer CQL Library Name validation. 
- Corrected CQL Library Name validation error message(QA feedback). 

MAT-3651: Updated cql library name validation error, fixed test cases

---

src/__mocks__/@madie/madie-patient.tsx
src/components/editMeasure/EditMeasure.test.tsx
src/components/editMeasure/EditMeasure.tsx
src/types/madie-madie-patient.d.ts

Jira Ticket: [MAT-3559](https://jira.cms.gov/browse/MAT-3559)

Import madie paitent home component

---

package-lock.json
package.json
src/components/editMeasure/EditMeasure.test.tsx
src/components/editMeasure/editMeasureNav/EditMeasureNav.tsx

Jira Ticket: [MAT-3706](https://jira.cms.gov/browse/MAT-3706)
* [ X] This PR has the JIRA linked.
* [ X] Required tests are included.
* [ X] No extemporaneous files are included (i.e Complied files or testing results).
* [ X] This PR is merging into the **correct branch**.
* [ X] This PR has NO significant security impact (i.e Changing auth methods, Adding a new user type, Adding a required but vulnerable package).
*  Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s …

update nav from Patient to Test Case; ref #MAT-3706

---

package-lock.json
src/components/createNewMeasure/CreateNewMeasure.test.tsx
src/components/createNewMeasure/CreateNewMeasure.tsx
src/components/measureList/MeasureList.tsx
src/models/Measure.ts
src/models/MeasureSchemaValidator.ts
src/models/MeasureScoring.ts

Jira Ticket: [MAT-3798](https://jira.cms.gov/browse/MAT-3798)
- Add enum for validating Measure Scoring
- Update measureScoring typing to use new enum or empty string for default selections
- Validate measure scoring is present and is a member of the measure scoring enum
- Replace measure scoring placeholder dropdown with enum values
- Display Measure Scoring on Measure List
*  The tests appropriately test …

[MAT-3798] Measure Scoring Validation and Display

---

src/components/editMeasure/EditMeasure.tsx
src/components/editMeasure/editMeasureNav/EditMeasureNav.tsx

Jira Ticket: [MAT-3706](https://jira.cms.gov/browse/MAT-3706)

update patients route to test-cases; ref #MAT-3706

---

package-lock.json
src/api/useMeasureServiceApi.tsx
src/components/measureLanding/MeasureLanding.test.tsx
src/components/measureLanding/MeasureLanding.tsx
src/components/measureList/MeasureList.tsx
src/components/newMeasure/NewMeasure.test.tsx
src/components/newMeasure/NewMeasure.tsx

Jira Ticket: [MAT-3813](https://jira.cms.gov/browse/MAT-3813)

Feature/mat 3813 all & my measures

---

src/components/newMeasure/NewMeasure.tsx

remove search field as search functionality is not yet implemented

---

.github/CODEOWNERS
.github/pull_request_template.md
src/components/measureLanding/MeasureLanding.tsx
src/components/measureList/MeasureList.tsx
src/components/newMeasure/NewMeasure.tsx

Jira Ticket: [MAT-3891](https://jira.cms.gov/browse/MAT-3891): Update MADiE Landing Page Post Log in
- updated route: /measure to /measures

MAT-3891 updated route: /measure to /measures

---

package-lock.json

Jira Ticket: [MAT-0000](https://jira.cms.gov/browse/MAT-0000)

slack/audit_warnings: fixing an audit issue

---

src/api/useMeasureServiceApi.tsx
src/components/measureEditor/MeasureEditor.test.tsx

Jira Ticket: [MAT-3892](https://jira.cms.gov/browse/MAT-3892)

modify update URI for update measure call to include measure ID

---

src/api/useMeasureServiceApi.tsx
src/components/measureGroups/MeasureGroups.test.tsx
src/components/measureGroups/MeasureGroups.tsx
src/models/Measure.ts
src/models/MeasurePopulation.ts

Jira Ticket: [MAT-3912](https://jira.cms.gov/browse/MAT-3912)

MAT-3912: Associate CQL Definition with measure group population

---

src/components/editMeasure/measureDetails/MeasureDetails.test.tsx
src/components/editMeasure/measureDetails/MeasureDetails.tsx
src/components/editMeasure/measureDetails/MeasureDetailsSidebar.tsx
src/components/measureGroups/MeasureGroups.tsx

Jira Ticket: [MAT-3565](https://jira.cms.gov/browse/MAT-3565)

MAT-3565 add test id for side bar nav

---

src/components/editMeasure/measureDetails/MeasureDetails.test.tsx
src/components/editMeasure/measureDetails/MeasureDetails.tsx
src/components/editMeasure/measureDetails/measureCopyright/MeasureCopyright.test.tsx
src/components/editMeasure/measureDetails/measureCopyright/MeasureCopyright.tsx
src/models/Measure.ts

Jira Ticket: [MAT-3572](https://jira.cms.gov/browse/MAT-3572)

MAT-3572 metadata copyright

---

src/components/editMeasure/measureDetails/measureInformation/MeasureInformation.tsx
src/components/editMeasure/measureDetails/measureInformation/__snapshots__/MeasureInformation.test.tsx.snap

Jira Ticket: [MAT-3974](https://jira.cms.gov/browse/MAT-3974)

MAT-3974: Modify display elements to retain white space in measure details

---

src/components/editMeasure/measureDetails/MeasureDetails.test.tsx
src/components/editMeasure/measureDetails/MeasureDetails.tsx
src/components/editMeasure/measureDetails/measureDisclaimer/MeasureDisclaimer.test.tsx
src/components/editMeasure/measureDetails/measureDisclaimer/MeasureDisclaimer.tsx
src/models/Measure.ts

Jira Ticket: [MAT-3581](https://jira.cms.gov/browse/MAT-3581)

Mat 3581 meta data disclaimer

---

src/components/measureGroups/MeasureGroupPopulationSelect.tsx
src/components/measureGroups/MeasureGroups.test.tsx
src/components/measureGroups/MeasureGroups.tsx

Jira Ticket: [MAT-4077](https://jira.cms.gov/browse/MAT-4077)

MAT-4077 Provide measure groups for Measure Population/Exclusion

---

package-lock.json
src/api/useElmTranslationServiceApi.ts

Jira Ticket: [MAT-4076](https://jira.cms.gov/browse/MAT-4076)
- Added Security for Cql to Elm translation service, So modified the api call to translator by adding Authorization header.

Calling translation service with access token

---

src/components/editMeasure/editMeasureNav/EditMeasureNav.tsx

Jira Ticket: [MAT-4094](https://jira.cms.gov/browse/MAT-4094)

MAT-4094 fix wrong 404 page error

---

src/components/newMeasure/CreateNewMeasureDialog.tsx
src/components/newMeasure/CreteNewMeasureDialog.test.tsx

Jira Ticket: [MAT-4065](https://jira.cms.gov/browse/MAT-0000)

MAT-4065a: Update style presentation for dialog to avoid confusion

---

package-lock.json
package.json
src/components/newMeasure/NewMeasure.tsx

Jira Ticket: [MAT-3366](https://jira.cms.gov/browse/MAT-3366)
This PR updates the measureList page by adding references to tabs in search paramaters to allow users to preserve tab location within url.
This PR updates design system to .8 and imports the loading spinner defined there.
Conditionally render loading spinner during first initial load.
*  The tests appropriately test the new code, including edge …

Mat-3366, Satisfy remaining measureListPage requirements
